---

# Add the apt repo off the maintainer of Debian's PHP packages, Ond?ej Sur?.
# This contains several php versions he maintains for multiple debian releases.
# See more : https://deb.sury.org/

- name:             fetch aptkey for deb.sury.org
  apt_key:          url="https://packages.sury.org/php/apt.gpg"
                    id=4A7A714D
                    state=present

- name:             add php channel from packages.sury.org to apt repos
  apt_repository:   repo="deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
                    state=present
                    filename="php.sury.org"
                    update_cache=yes
  register:         phpfpm_aptrepo

- name:             update packages
  apt:              upgrade=yes
  when:             phpfpm_aptrepo.changed

- name:             install php-fpm
  apt:              name={{ item }}
                    state=present
  with_items:       "{{ pkgs_phpfpm }}"
