---

- name:             restart php5.6-fpm
  service:          name=php5.6-fpm
                    state=restarted
                    enabled=yes

- name:             restart php7.0-fpm
  service:          name=php7.0-fpm
                    state=restarted
                    enabled=yes

- name:             restart php7.1-fpm
  service:          name=php7.1-fpm
                    state=restarted
                    enabled=yes

- name:             restart php7.2-fpm
  service:          name=php7.2-fpm
                    state=restarted
                    enabled=yes

- name:             reload nginx
  service:          name=nginx
                    state=reloaded
                    enabled=yes
